---
ansible_network_os: ios
ansible_connection: network_cli
ansible_user: cisco
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_password: cisco

show_commands:
  - show clock
  - show version
  - show interfaces
  - show running-config
